sudo: required
services:
  - docker

before_install:
  - docker build -t varun508/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true varun508/react-test npm test

after_success:
  - docker build -t varun508/multi-client ./client
  - docker build -t varun508/multi-nginx ./nginx
  - docker build -t varun508/multi-server ./server
  - docker build -t varun508/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push varun508/multi-client
  - docker push varun508/multi-nginx
  - docker push varun508/multi-server
  - docker push varun508/multi-worker